jetpack-compose/jetpack-compose-awesome

README.md
Hey, it would be so cool if you could include this Twitter bot in your README.md
Thanks!
=> Add Jetpack Compose Twitter Bot in the README.md

README.md
- Add compose-markdown lib reference
- Add multinavcompose lib reference
=> Update libraries section

README.md
The project - https://github.com/krottv/compose-sliders
=> Add project to Libraries - UI

README.md
- Added link to page which has 11+ articles on compose covering many use-cases and implementations.
- GitHub repository which contains samples on implementing many composables.
- Compose app built with new revamped guide to app architecture and different layers.
=> Updated readme with new compose Docs & Project

README.md
Add [Konfetti](https://github.com/DanielMartinus/Konfetti) to the UI library section
=> Add UI library - Konfetti

README.md
Added 3 articles on jetpack compose.
Animations in Jetpack Compose with examples
Jetpack compose — Dependency injection with Dagger/HILT
Jetpack Compose: MVVM State management in a simple way
=> Added articles on Jetpack Compose

README.md
Article - Intro showcase view in Jetpack Compose — Android
Libraries:
- Intro Showcase View using Jetpack Compose
- Jetpack-compose-animations-examples
=> Added one article, two libraries, and updated stars of existing projects.

README.md
Add [heart-switch](https://github.com/popovanton0/heart-switch) to the UI library section
=> Add heart-switch

README.md
- Added new Articles, Libraries and Sample projects
=> - Added new libraries, sample projects and blogs

README.md
"App Project" & "Videos" Link doesn't work. this can help to work.
=> Contents Link Fix

README.md
There is something new as "Android Basics with Compose Course" ve "Compose performance Doc"  which are announced in Google I/O. I think adding them will be really beneficial.
=> Request for the add new articles on docs.

README.md
- Currently material2 is supported and material3 plans to be supported within June.
- Please check, https://github.com/seyoungcho2/ComposeDynamicTheme for detail
<br>
<p align="center">
<a href="https://opensource.org/licenses/Apache-2.0"><img alt="License" src="https://img.shields.io/badge/License-Apache%202.0-blue.svg"/></a>
<a href="https://android-arsenal.com/api?level=26"><img alt="API" src="https://img.shields.io/badge/API-26%2B-brightgreen.svg?style=flat"/></a>
</p>
Dynamic Theme is a Material Design-based Theme Management System for Android Jetpack Compose. Up until now, changing the theme on Android has been a very difficult task. Dynamic Theme was created to make Android's theme management easy. Theming can be applied by simply adding 'ProvidesTheme' to the top-level declaration …
=> Add Compose Dynamic Theme Library

README.md
https://github.com/omkar-tenkale/ExplodingComposable
A Jetpack Compose utility library to add explosive dust effect animation to any composable
=> Add Exploding Composable UI library

README.md
https://github.com/popovanton0/Blueprint
=> Add a blueprint library

README.md
Navigation bar with a number of preset animations written in Jetpack Compose
=> Add Animated Navigation Bar library

README.md
Article about migrating to Jetpack Compose Multiplatform
=> Add Jetpack Compose Multiplatform article

README.md
The article describes how to use FlowLayout, and covers new and old APIs.
=> Add FlowLayout article

README.md
Articles
1. [Gestures in Jetpack compose — All you need to know ](https://medium.com/canopas/gestures-in-jetpack-compose-all-you-need-to-know-part-1-9d26570e56bb)
2. [How to Use Render Effects in Jetpack Compose for Stunning Visuals](https://blog.canopas.com/how-to-use-render-effects-in-jetpack-compose-for-stunning-visuals-01287d7f00db)
Libraries
1. [compose-animated-navigationbar](https://github.com/canopas/compose-animated-navigationbar)
2. [rich-editor-compose](https://github.com/canopas/rich-editor-compose)
=> Added two articles & libraries

README.md
https://github.com/Calvin-LL/Reorderable
https://github.com/Calvin-LL/AutoLinkText
=> Add two libraries

README.md
Add CoinWatch to apps section.
CoinWatch is a cryptocurrency app providing real-time coin prices, price histories, and market data.
The app is built using the latest [Android architecture components](https://developer.android.com/topic/architecture/recommendations) - resulting in a scalable, modularised and testable app.
=> Add CoinWatch

README.md
https://github.com/IlyaPavlovskii/YouTubePlayer
=> Add youtube compose multiplatform player.
